name: Deploy Matrix Node
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          # 引用你在 Settings 里存的名字
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: matnode
          directory: .
